apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b1dy4ub1m-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b1dy4ub1m-go 
  name: b1dy4ub1m-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b1dy4ub1m-go 
